name: ball_on_a_budget_planner
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  flutter_bloc: ^6.1.3
  bloc: ^6.1.3

  flutter_spinkit: ^5.0.0
  easy_localization: ^3.0.0
  carousel_pro: ^1.0.0
  intl: ^0.17.0-nullsafety.2
  font_awesome_flutter: ^9.0.0
  rxdart: ^0.26.0
  connectivity: ^3.0.3
  shared_preferences: ^2.0.5
  flutter_masked_text: ^0.8.0
  fl_chart: ^0.35.0
  flutter_circular_chart_two: ^0.1.2
  date_format: ^2.0.2
  flutter_speed_dial: ^3.0.5
  jiffy: ^4.1.0
  flutter_local_notifications: ^5.0.0+1
  package_info: ^2.0.0

  cloud_firestore: ^1.0.2
  firebase_core: ^1.10.0
  google_fonts: ^2.0.0

  flutter_secure_storage: ^4.1.0

  date_range_picker: ^1.0.7
  
  flutter_launcher_icons: ^0.9.0

  tuple: ^2.0.0
  analog_clock: ^0.0.4

  dio: ^4.0.1
  flutter_native_splash: ^1.2.1
  file_picker: ^4.2.1
  advance_pdf_viewer: ^2.0.0
  path_provider: ^2.0.4
  universal_html: ^2.0.8
  searchable_dropdown: ^1.1.3
  pdf: ^3.6.1
  permission_handler: ^8.1.6
  flutter_file_manager: ^0.2.0
  flutter_full_pdf_viewer: ^1.0.6
  path_provider_ex: ^1.0.1
  printing: ^5.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^3.0.0
  build_runner: ^1.0.0

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: "launcher_icon"
  ios: true

flutter_native_splash:
  image: assets/images/icon.png
  color: ffffff

flutter:


  uses-material-design: true
  assets:
   - assets/images/
   - assets/translations/
   - icons/
   
  fonts:
   - family: BanklinIcons
     fonts:
      - asset: assets/fonts/BanklinIcons.ttf
